apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Chart.Version }}"
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          env:
            - name: POSTGRESQL_USER
              value: {{ .Values.database.default.user }}
            - name: POSTGRESQL_PASSWORD
              value: "{{ .Values.database.default.password }}"
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.database.default.name }}
          ports:
            - name: postgres
              containerPort: {{ .Values.port }}
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: db-data
          emptyDir: { }