image:
  repository: romanowalex/backend-todo-list
  tag: v2.0

port: 8080
profile: k8s

ingress:
  enabled: false

database:
  host: postgres

secrets:
  - name: GOOGLE_CLIENT_ID
    secretName: credentials
    secretKey: google-client-id
  - name: GOOGLE_CLIENT_SECRET
    secretName: credentials
    secretKey: google-client-id

metrics:
  path: "/backend/manage/prometheus"
  username: management
  password: test

liveness:
  path: "/backend/manage/health/liveness"

readiness:
  path: "/backend/manage/health/readiness"

resources:
  requests:
    cpu: 1
    memory: 2048Mi
  limits:
    cpu: 1
    memory: 2048Mi