spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_list
    username: program
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

oauth2:
  login:
    redirect-uri: http://localhost:3000
