spring:
  application.name: todo-list
  main.banner-mode: off
  profiles.active: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: off

management:
  endpoints:
    web:
      base-path: /manage
      exposure.include: info,health,loggers
  health:
    diskspace.enabled: false
  endpoint:
    health.show-details: always

springdoc:
  paths-to-match: /api/**
  api-docs.path: /api-docs

oauth2:
  login:
    redirect-uri: /