spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres}:${DATABASE_PORT:5432}/${DATABASE_NAME:todo_list}
    username: ${DATABASE_USER:program}
    password: ${DATABASE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

oauth2:
  login:
    redirect-uri: http://todo-list.ru/
