image:
  repository: romanowalex/frontend-todo-list
  tag: v2.0

port: 3000

ingress:
  enabled: true
  name: todo-list
  domain: romanow-alex.ru

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi
