image:
  pullPolicy: IfNotPresent
  repository: postgres
  tag: 15

port: 5432

users:
  - name: program
    password: test

defaultDatabase:
  name: postgres
  user: postgres
  password: postgres

datases:
  - name: todo_list
    user: program

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi