apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: todo-list
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/version: "{{ .Values.version }}"
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: todo-list
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "postgres:{{ .Values.version }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: {{ .Values.default_database.user }}
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.default_database.password }}"
            - name: POSTGRES_DB
              value: {{ .Values.default_database.name }}
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          ports:
            - name: postgres
              containerPort: {{ .Values.port }}
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-config-map
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: db-data
        - name: postgres-config-map
          configMap:
            name: {{ .Release.Name }}-configmap